- name: check if the host contains .az for azure
  become: true
  ansible.builtin.copy:
    src: files/azure.swap.sh
    dest: /var/lib/cloud/scripts/per-boot/swap.sh
    owner: root
    group: root
    mode: '755'

- name: run azure swap script
  become: true
  ansible.builtin.command: "/var/lib/cloud/scripts/per-boot/swap.sh"