- name: add .bash_aliases for all users
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: files/bash_alias.j2
    dest: "~/.bash_aliases"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - root
    - "{{ ansible_user_id }}"