- name: drop-in directory
  ansible.builtin.file:
    path: /etc/systemd/network/05-{{ ansible_default_ipv4.interface }}.network.d/
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: copy custom config
  ansible.builtin.template:
    src: files/01-custom.conf.j2
    dest: /etc/systemd/network/05-{{ ansible_default_ipv4.interface }}.network.d/01-custom.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: true
  notify: restart systemd-networkd