- name: upgrade all packages
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes
    autoclean: true
    autoremove: true
  become: true

- include_tasks: hostname.yml
- include_tasks: packages.yml
- include_tasks: bash.yml
- include_tasks: zsh.yml
#- include_tasks: dns_update.yml
#- include_tasks: br0.yml
#- include_tasks: loopback.yml
- include_tasks: swap.yml