- name: add dns to resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ resolvconf_dns_server }}"
    state: present
  become: true
  when: resolvconf_dns_server is defined

- name: Register Device/VM to Ubuntu Pro
  ansible.builtin.shell: sudo pro attach {{ ubuntu_pro_token }}
  become: true
  when: ansible_distribution == 'Ubuntu' and ubuntu_pro_token is defined

- name: upgrade all packages
  ansible.builtin.apt:
    upgrade: safe
    update_cache: yes
    autoclean: true
    autoremove: false
  become: true

- include_tasks: hostname.yml
- include_tasks: packages.yml

- include_tasks: user.yml
  when: create_user_enable == true

- name: add .bash_aliases for all users
  become: true
  become_user: "{{ item }}"
  ansible.builtin.template:
    src: files/bash_alias.j2
    dest: "~/.bash_aliases"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  loop:
    - root
    - "{{ ansible_user_id }}"




- include_tasks: zsh.yml
#- include_tasks: dns_update.yml
#- include_tasks: br0.yml
#- include_tasks: loopback.yml
- include_tasks: swap.yml