## This is a sample playbook to create swap file on linux
## This playbook will check if swap file exist, if not it will create one
## This playbook will check if the hostname contains .az (short for azure), if yes it will run the azure.yml file
## azure provides a temporary storage that can be used for swap file
- include_tasks: azure.swap.yml
  when: "'.az' in inventory_hostname"

- name: check if swap file exist in /swapfile
  become: true
  stat: 
    path: "/swapfile"
  register: swapfile
  when: "'.az' not in inventory_hostname" 

- name: check if swap file exist in /swapfile
  become: true
  stat: 
    path: "/swapfile"
  register: swapfile

- name: check if swap is on
  become: true
  ansible.builtin.command: "swapon -s | grep -v Filename"
  register: swap
  when: "'.az' not in inventory_hostname"
## When swap is on "swapon -s | grep -v Filename" will return a string
## so we are using that to verify is swap is on or not
## when its off, it will return nothing

- name: create swapfile
  when: (not swapfile.stat.exists) and ('.az' not in inventory_hostname) and (swap.stdout == '') 
  become: true
  ansible.builtin.command: "fallocate -l 2G /swapfile"
    
- name: set swapfile permission
  when: (not swapfile.stat.exists) and ('.az' not in inventory_hostname) and (swap.stdout == '') 
  become: true
  ansible.builtin.file:
    path: /swapfile
    mode: '600'

- name: format swap file
  become: true
  when: (not swapfile.stat.exists) and ('.az' not in inventory_hostname) and (swap.stdout == '') 
  ansible.builtin.command: "mkswap /swapfile"

- name: add to fstab
  when: (not swapfile.stat.exists) and ('.az' not in inventory_hostname) and (swap.stdout == '') 
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile swap swap defaults 0 0"

- name: turn on swap
  become: true
  ansible.builtin.command: "swapon -a"
  when: ('.az' not in inventory_hostname) and (swap.stdout == '') 

# - name: set swapiness
#   become: true
#   ansible.posix.sysctl:
#     name: vm.swapiness
#     value: "1"
