# Create the user and set up their environment
- name: Create user if not exists
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    state: present
    home: "{{ ansible_user_home }}"
    shell: /bin/bash
    create_home: true
  become: true

# todo: create a variable for create new user enable