# Create the user and set up their environment
- name: Create user if not exists
  ansible.builtin.user:
    name: "{{ create_user }}"
    state: present
    create_home: true
  become: true

- name: Add user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ create_user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  become: true

- name: Add ssh public key for the user
  ansible.posix.authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ ssh_key_link }}"

# todo: create a variable for create new user enable