- name: install zsh and zsh suggestion
  ansible.builtin.apt:
    name:
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    state: present
    update_cache: yes
  become: true

- name: install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: {{ item.home }}/.oh-my-zsh
    update: true
  become: true
  become_user: {{ item.user }}
  loop:
    - {user: '{{ansible_user_id}}', home: '/home/{{ ansible_user_id }}'}
    - {user: 'root', home: '/root'}

- name: copy zsh custom config
  ansible.builtin.copy:
    src: files/zshrc
    dest: {{ item.home }}/.zshrc
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0644
  become: true
  become_user: "{{ item.user }}"
  loop:
    - {user: '{{ansible_user_id}}', home: '/home/{{ ansible_user_id }}'}
    - {user: 'root', home: '/root'}

- name: change users shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true
  become_user: {{ item }}
  loop:
    - '{{ansible_user_id}}'
    - 'root'
