- name: install zsh and zsh suggestion
  ansible.builtin.apt:
    name:
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    state: present
    update_cache: yes
  become: true

- name: install oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    update: true
  become: true
  become_user: "{{ item }}"
  loop:
    - root
    - "{{ ansible_user_id }}"

- name: copy zsh custom config
  ansible.builtin.copy:
    src: files/zshrc
    dest: ~/.zshrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  become: true
  become_user: "{{ item }}"
  loop:
    - root
    - "{{ ansible_user_id }}"

- name: change users shell to zsh
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true
  become_user: "{{ item }}"
  loop:
    - '{{ ansible_user_id }}'
    - 'root'
