# this tasks uses each host's hostname and sets them up in /etc/hosts file on each host
# This allowss hosts to communicate with each other internally using their hostnames

- name: get wireguard ip for host from wg-server.conf file
  ansible.builtin.shell: (cat /etc/wireguard/{{ wg_iface }}.conf | grep Address | awk '{print $3}' | awk -F/ '{print $1}')
  register: wireguard_ip
  become: true
  become_method: sudo

- name: print wireguard ip for host
  debug:
    msg: "{{ hostvars[item].wireguard_ip.stdout }}"
  loop: "{{ groups['all'] }}"

# check bellow for more info on how to use this task or if you are getting errors
# make sure your hosts file is clean and only has hosts that you are using, remove extra hosts and empty host groups
- name: Add IP address of all hosts to all hosts as text block
  blockinfile:
    dest: /etc/hosts
    block: |
      {% for item in groups['all'] %}
      {{ hostvars[item].wireguard_ip.stdout }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}
      {% endfor %}
    state: present
    backup: false
  become: true
  become_method: sudo
  loop: "{{ groups['all'] }}"

# note that if u have any extra hosts in your inventory file that you are not using, this will throw an error
# keep your inventory file clean


# - name: Add IP address of all hosts to all hosts
#   lineinfile:
#     dest: /etc/hosts
#     lineafter: "# managed by ansible"
#     insertbefore: "# end of managed by ansible"
#     line: "{{ hostvars[item].wireguard_ip.stdout }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
#     state: present
#     backup: true
#   become: true
#   with_items: "{{ groups['all'] }}"

