- include_tasks: sysctl.yml

- name: upgrade all packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: yes
  become: true
  
- name: install wireguard
  ansible.builtin.apt:
    name:
      - wireguard
      - wireguard-tools
      - resolvconf
    install_recommends: yes
    state: present
    update_cache: yes
  become: true

- name: ensure wireguard kernel module is loaded
  ansible.builtin.modprobe:
    name: wireguard
    state: present
  become: true

- name: ensure wireguard config is stopped
  ansible.builtin.command: wg-quick down wg-server
  become: true
  ignore_errors: true

- name: copy wireguard config
  ansible.builtin.copy:
    src: files/{{ inventory_hostname }}.conf
    dest: /etc/wireguard/wg-server.conf
    owner: root
    group: root
    mode: 0600
  become: true
  notify: restart wg-server

- name: ensure wireguard config is loaded
  ansible.builtin.command: wg-quick up wg-server
  become: true

- name: ensure wg-quick@wg-server.service is started and enabled at boot
  ansible.builtin.service:
    name: wg-quick@wg-server.service
    state: started
    enabled: yes
  become: true

- name: get wireguard ip for host from wg-server.conf file
  ansible.builtin.shell: (cat /etc/wireguard/wg-server.conf | grep Address | awk '{print $3}' | awk -F/ '{print $1}')
  register: wireguard_ip
  become: true
## use {{ wireguard_ip.stdout }} to get a ip range

- name: wireguard ip
  debug:
    msg: "wireguard_ip {{ wireguard_ip.stdout }}"