- include_tasks: sysctl.yml

- name: upgrade all packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: yes
  become: true
  
- name: install wireguard
  ansible.builtin.apt:
    name:
      - wireguard
      - wireguard-tools
      - resolvconf
    install_recommends: yes
    state: present
    update_cache: yes
  become: true

- name: ensure wireguard kernel module is loaded
  ansible.builtin.modprobe:
    name: wireguard
    state: present
  become: true

- name: ensure wireguard config is stopped
  ansible.builtin.command: wg-quick down wg-server
  become: true
  ignore_errors: true

- name: copy wireguard config
  ansible.builtin.copy:
    src: files/{{ inventory_hostname }}.conf
    dest: /etc/wireguard/wg-server.conf
    owner: root
    group: root
    mode: 0600
  become: true
  notify: restart wg-server

# - name: ensure wireguard config is loaded
#   ansible.builtin.command: wg-quick up wg-server
#   become: true
#   args:
#     creates: /etc/wireguard/wg-server.conf

- name: ensure wg-quick@wg-server.service is started and enabled at boot
  ansible.builtin.service:
    name: wg-quick@wg-server.service
    state: restarted
    enabled: yes
  become: true
