roles:
  - src: git+https://github.com/geerlingguy/ansible-role-docker
    version: 7.4.1
    name: docker

collections:
  - name: community.docker
  - name: prometheus.prometheus
  - name: ansible.posix
  - name: community.general