- name: setup portainer_agent
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:latest
    pull: true
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "{{ portainer_agent_bind_ip }}:29001:9001"
    state: started