- name: Remove temporary working directory
  ansible.builtin.file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: absent

- name: Create temporary working directory
  ansible.builtin.file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: directory
    mode: '0775'

- name: Get rclone stable version
  ansible.builtin.unarchive:
    src: https://downloads.rclone.org/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}.zip
    dest: "{{ rclone_setup_tmp_dir }}"
    remote_src: true
    mode: 0744
    creates: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}"

- name: Get list of files extracted from the rclone archive
  ansible.builtin.find:
    path: "{{ rclone_setup_tmp_dir }}"
    depth: 2
    file_type: directory
  register: rclone_archive

- name: Copy rclone binary
  ansible.builtin.copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone"
    dest: "/usr/local/bin/rclone"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  become: true

- name: Make dir for local manpages
  ansible.builtin.file:
    path: '{{ rclone_man_pages.PATH }}'
    state: directory
    mode: '0775'
    owner: '{{ rclone_man_pages.OWNER }}'
    group: '{{ rclone_man_pages.GROUP }}'
  become: true
  when: install_manpages

- name: Copy rclone manpage
  ansible.builtin.copy:
    src: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_arch }}/rclone.1"
    dest: "{{ rclone_man_pages.PATH }}/rclone.1"
    mode: '0644'
    owner: root
    group: root
    remote_src: true
  become: true
  when: install_manpages

- name: Update mandb
  ansible.builtin.command: mandb
  become: true
  changed_when: false
  when: install_manpages