- name: Install Fail2Ban
  ansible.builtin.apt:
    name:
      - fail2ban
    state: present
    autoclean: true
    force_apt_get: true
    install_recommends: true
    update_cache: true
  become: true

- name: Fail2Ban configuration
  ansible.builtin.template:
    src: files/ssh_fail2ban.conf.j2
    dest: /etc/fail2ban/jail.d/ssh.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart fail2ban
