- name: ensure iptables is installed
  ansible.builtin.apt:
    name:
      - nftables
      - netfilter-persistent 
      - iptables
      - iptables-persistent
    state: present
    clean: true
    install_recomends: true
    lock_timeout: 60
    update_cache: true
  become: true

- name: starting iptables