- name: ensure iptables is installed
  ansible.builtin.apt:
    name:
      - nftables
      - netfilter-persistent 
      - iptables
      - iptables-persistent
    state: present
    install_recomends: true
    update_cache: true
  become: true

- name: starting iptables
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true
  become: true
