- name: uninstall iptables and ufw to prevent conflicts
  ansible.builtin.apt:
    name:
      - iptables
      - ufw
    state: absent
  become: true

- name: ensure nftables is installed
  ansible.builtin.apt:
    name:
      - nftables
      - netfilter-persistent 
      - iptables-persistent
    state: present
    autoclean: true
    clean: true
    force_apt_get: true
    install_recommends: true
    lock_timeout: 60
    update_cache: true
  become: true

- name: nftables rules
  ansible.builtin.template:
    src: files/nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
  become: true
  notify: restart nftables

- name: starting nftables
  ansible.builtin.service:
    name: nftables
    state: started
    enabled: true
  become: true
