- name: disable iptables
  ansible.builtin.service:
    name: iptables
    state: stopped
    enabled: false
  become: true
  ignore_errors: true

- name: disable ufw
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: false
  become: true 
  ignore_errors: true
- name: ensure nftables is installed
  ansible.builtin.apt:
    name:
      - nftables
    state: present
    autoclean: true
    clean: true
    force_apt_get: true
    install_recommends: true
    lock_timeout: 60
    update_cache: true
  become: true

- name: nftables rules
  ansible.builtin.template:
    src: files/nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
  become: true
  notify: restart nftables

- name: starting nftables
  ansible.builtin.service:
    name: nftables
    state: started
    enabled: true
  become: true
