- name: sshd_config
  ansible.builtin.template:
    src: files/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '644'
    backup: yes
  become: true
  notify: restart sshd
