- name: start nftables
  ansible.builtin.service:
    name: nftables.service
    state: started
  become: true
  become_method: sudo

- name: restart nftables
  ansible.builtin.service:
    name: nftables.service
    state: restarted
  become: true
  become_method: sudo

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban.service
    state: restarted
  become: true
  become_method: sudo

- name: restart ufw
  ansible.builtin.service:
    name: ufw.service
    state: restarted
  become: true
  become_method: sudo
  
- name: restart docker
  ansible.builtin.service:
    name: docker.service
    state: restarted
  become: true